### ISSUE TITLE
Scanning in loop                                                                                                                                                                                                                                                                                                                          

### ISSUE THREAD

**Issue by sainianu** [u-blox/Android-u-blox-BLE#5]
Hi
If i download and compile the provided source code , it doesn't give any result for scanning via BLE but if i run the app from provided apk it detects and list the devices available for connection. 
Any Help regarding the source code issue would be appreciated!

Thankyou

**Comment by perssonmagnus** [comment]
Hi,

One possible cause of this is due to different permissions required for different Android versions or API levels. Please check https://developer.android.com/guide/topics/connectivity/bluetooth/permissions and check the permissions requested in the code vs the target API level.

Best Regards,
Magnus

**Comment by skibz** [comment]
@sainianu getting results from a bluetooth low energy scan requires location permissions

**Comment by perssonmagnus** [comment]
Close as no further comments.
